name: CI workflow

on: 
    push:
        branches: ["main"]
    pull_request: 
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name : Install dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run: | 
                flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
            - name: Run unit tests with nose
              run:
                nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

            # Add Notification Step
            - name: Notify on Failure
              if: failure()
              run: echo "The CI workflow failed. Please check the build logs for more details."  # Add your notification logic here

            # Placeholder for Performance Testing
            - name: Performance Testing
              run: |
                # Add your performance testing commands here
                echo "Running performance tests..."
